name: Branch Naming Convention
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sumit844/reactjs/.github/workflows/reusable_workflow.yml@main
        with:
          environment: "DEV"
