name: Branch Naming Convention
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout code because using workflow file
        run: echo "welcome"
      - uses: sumit844/reactjs/.github/workflows/reusable_workflow.yml
        with:
          environment: "DEV"
