name: Branch Naming Convention
on:
  push:
    branches:
      - main
  label:
    types:
      - created
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        run: echo "Checking branch naming convention"
      - name: calling the reusable workflow.
        uses: ./resuable_workflow.yml
        with:
          environment: "DEV"
