name: Contineous Integration Workflow

on:
  push:
    branches: main

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Building FE"
      - run: npm run ci
      - run: npm run build --if-present
      - run: npm test
