name: Reusable Workflow for Build
on:
  workflow_call:
    inputs:
      environment:
        description: "Testing it on DEV"
        required: true
        type: string
jobs:
  calling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: This is the environment
        run: echo "this is the environment name ${{inputs.environment}}"
